# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true

    # BƯỚC GỠ LỖI ĐỂ KIỂM TRA CẤU TRÚC THƯ MỤC
    - name: Debug Workspace Structure
      run: |
        echo "--> Running in directory: $(pwd)"
        echo "--> File structure after checkout:"
        ls -laR
        echo "-------------------------------------"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Restart PM2 process
      run: pm2 restart BackEndAPI