name: Node.js CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Xóa folder BackEnd cũ
    - name: Clean BackEnd directory
      run: |
        cd ${{ github.workspace }}
        rm -rf BackEnd
        echo "Cleaned old BackEnd directory"
        ls -la

    # Checkout code vào folder BackEnd
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: BackEnd

    # Debug structure
    - name: Check structure
      run: |
        echo "Working directory: $(pwd)"
        echo "Workspace: ${{ github.workspace }}"
        ls -la
        echo "--- BackEnd folder content ---"
        ls -la BackEnd/
        echo "--- Looking for package.json ---"
        find BackEnd -name "package.json"

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    # Install dependencies
    - name: Install dependencies
      run: |
        cd BackEnd
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "package.json not found in BackEnd root"
          ls -la
          find . -name "package.json"
          exit 1
        fi

    # Create .env
    - name: Create .env file
      run: |
        cd BackEnd
        echo "${{ secrets.ENV_FILE }}" > .env
        echo ".env file created"

    # Start PM2
    - name: Start PM2
      run: |
        cd BackEnd
        pm2 delete BackEndAPI || true
        pm2 start server.js --name BackEndAPI
        pm2 list