name: Node.js CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
        path: _work/BackEnd  # Checkout trực tiếp vào _work/BackEnd

    # BƯỚC GỠ LỖI ĐỂ KIỂM TRA CẤU TRÚC THƯ MỤC
    - name: Debug Workspace Structure
      run: |
        echo "--> Running in directory: $(pwd)"
        echo "--> File structure after checkout:"
        ls -laR _work
        echo "-------------------------------------"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '_work/BackEnd/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: _work/BackEnd 

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.ENV_FILE }}" > .env
      working-directory: _work/BackEnd 

    - name: Restart PM2 process
      run: |
        # Xóa cấu hình PM2 cũ nếu tồn tại
        pm2 delete BackEndAPI || true
        # Khởi động lại với đường dẫn tương đối
        pm2 start server.js --name BackEndAPI
      working-directory: _work/BackEnd 