name: Node.js CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Cleanup toàn bộ workspace
    - name: Clean workspace
      run: |
        cd ${{ github.workspace }}
        rm -rf ./*
        rm -rf ./.[!.]*
        ls -la

    # Checkout trực tiếp vào workspace root (không dùng path)
    - uses: actions/checkout@v4
      with:
        clean: true

    # Debug cấu trúc thư mục
    - name: Debug Workspace Structure  
      run: |
        echo "--> Running in directory: $(pwd)"
        echo "--> Workspace: ${{ github.workspace }}"
        echo "--> File structure after checkout:"
        ls -la
        echo "-------------------------------------"

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Cài dependencies
    - name: Install dependencies
      run: npm ci
      working-directory: BackEnd

    # Tạo file .env từ secrets
    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.ENV_FILE }}" > .env
      working-directory: BackEnd

    # Khởi động lại PM2 process
    - name: Start PM2 process
      run: |
        pm2 delete BackEndAPI || true
        pm2 start server.js --name BackEndAPI
      working-directory: BackEnd